### ISSUE TITLE
Please push version 2.0.0

### ISSUE THREAD

**Issue by xJuvi** [requtize/assetter#2]
Hi,
please create a version 2.0.0 release on github. Packagist can find only version 1.2.1 so i had install an old version. You composer.json file is updated but you need to create a new release to push the version.

Thanks!

**Comment by adambanaszkiewicz** [comment]
I'm working on version 2.0 :) In this week I want to add the 'collections' functionality and release the 2.0 version.

Keep in touch.

**Comment by adambanaszkiewicz** [comment]
Version 2.0 released. Please feel free to check it out.
